version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgrespassword"
    ports:
    - "5434:5432"
volumes:
  db_data:
